# Generated by Django 5.2.8 on 2026-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm_chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("response_text", models.TextField()),
                ("response_data", models.JSONField()),
                ("hit_count", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
