# Generated by Django 5.2.8 on 2026-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm_chat", "0003_project_chat_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                    ("developer", "Developer"),
                    ("tool", "Tool"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="error_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="request_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="llmcall",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("generation_in_progress", "Generation In Progress"),
                    ("generation_completed", "Generation Completed"),
                    ("generation_failed", "Generation Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
